version: '3'
services:
    revealjs:
        build: .
        command: npm start
        ports: 
            - "8000:8000"
        volumes:
            - ${HTML_ROOT}/index.html:/usr/share/reveal.js/index.html
            - ${HTML_ROOT}/markdown:/usr/share/reveal.js/markdown
