version: '3'


services:
    reveal-js:
        env_file: 
            - server.env
        build: .
        command: bash -c "exec node /usr/bin/http-server-with-auth -p 8000 --username $${USERNAME} --password $${PASSWORD}"
        ports:
            - "8000:8000"
        volumes:
            - ${HTML_ROOT}/index.html:/usr/share/reveal.js/index.html
            - ${HTML_ROOT}/data:/usr/share/reveal.js/data
        depends_on: 
            - multiplex-server

    multiplex-server:
        build: .
        command: node plugin/multiplex
        ports:
            - "1948:1948"

    client:
        build: .
        command: npm start
        ports:
            - "8001:8000"
        volumes:
            - ${HTML_ROOT}/index_client.html:/usr/share/reveal.js/index.html
            - ${HTML_ROOT}/data:/usr/share/reveal.js/data
        depends_on: 
            - multiplex-server
